django_project/django_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^browserid/', include('django_browserid.urls')),
    url(r'^spec/', include('kind.urls', namespace='kind')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls')),
    url(r'^$', include('kind.urls', namespace='kind')),
)

kind/urls.py
from django.conf.urls import patterns, url

from kind import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<specification_id>\d+)/form/$', views.form_view, name='form_view'),
    url(r'^(?P<specification_id>\d+)/vote/$', views.vote, name='vote'),
)

kindrms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^browserid/', include('django_browserid.urls')),
    url(r'^spec/', include('kind.urls', namespace='kind')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('kind.urls', namespace='kind')),
)

kind/models.py
from django.db import models
from django.forms import ModelForm

import datetime
from django.utils import timezone

class Specification(models.Model):
    spec_name = models.CharField(max_length=200)
    create_date = models.DateTimeField('date created')

    # This function is maintained only as a template for later functions
    def was_created_recently(self):
        #return self.create_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.create_date < now

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.spec_name

class Requirement(models.Model):
    MAX_SHORT_TEXT_LENGTH = 55;

    spec = models.ForeignKey(Specification)
    heading_text = models.CharField(max_length=200, blank=True)
    body_text = models.CharField(max_length=2000, blank=True)
    doc_sort_order = models.IntegerField(default=0, null=False)
    def short_text(self):
        if len(self.heading_text):
            return "H: "+self.heading_text[0:Requirement.MAX_SHORT_TEXT_LENGTH];
        else:
            return "B: "+self.body_text[0:Requirement.MAX_SHORT_TEXT_LENGTH];

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.short_text();

class RequirementForm(ModelForm):
    class Meta:
        model = Requirement
        fields = '__all__'
        #fields = ['heading_text', 'body_text']
        # See also https://docs.djangoproject.com/en/1.6/topics/forms/modelforms/

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

sqleditoronline/models.py
from django.db import models
import datetime
from django.utils import timezone

class SqlTable(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question

class TableRow(models.Model):
    poll = models.ForeignKey(SqlTable)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text

kind/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic


from kind.models import Specification, Requirement, RequirementForm

class IndexView(generic.ListView):
    template_name = 'kind/index.html'
#    model = Specification
    context_object_name = 'latest_spec_list'

    def get_queryset(self):
        """Return the specifications."""
        return Specification.objects.order_by('-create_date')[:]


# Note: There's also a get_list_or_404() function, which works just as
# get_object_or_404() – except using filter() instead of get(). It 
# raises Http404 if the list is empty.
class DetailView(generic.DetailView):
    model = Specification
    template_name = 'kind/detail.html'

class ResultsView(generic.DetailView):
    model = Specification
    template_name = 'kind/results.html'

def form_view(request, specification_id): 
    if request.method == 'POST': # If the form has been submitted...
        form = RequirementForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...
            return HttpResponseRedirect('/thanks/') # Redirect after POST
    else:
        form = RequirementForm() # An unbound form

    return render(request, 'kind/results.html', {
        'form': form,
    })

def vote(request, specification_id): 
    return HttpResponse("You're voting on specification %s." % specification_id)

polls/views.py
from django.shortcuts import render

# Create your views here.

sqleditoronline/views.py
from django.shortcuts import render

# Create your views here.

django_project/kind/templates/kind/index.html
{% load browserid %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'kind/style.css' %}" />
<html>
  <head>
<link type="text/css" href="{{STATIC_URL}}js/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />
<script type="text/javascript" src="{{STATIC_URL}}js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/ui.core.js"></script>
<script src="{{STATIC_URL}}js/ui.datepicker.js" type="text/javascript"></script>
    {% browserid_css %}
  </head>
    <body>
      {% browserid_info %}

  <header>
      <div class="authentication">
        {% if user.is_authenticated %}
          {% browserid_logout text='Logout' %}
        {% else %}
          {% browserid_login text='Login' color='dark' %}
        {% endif %}
      </div>
      <h1>Specification list</h1>
    </header>
<article>

      <a href="{% url todo-lists %}">To-do Lists</a>
      <a href="{% url todo-mine %}">My Tasks</a>

{% if latest_spec_list %}
    <ul>
    {% for spec in latest_spec_list %}
        <li><a href="{% url 'kind:detail' spec.id %}">{{ spec.spec_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No specs are available.</p>
{% endif %}
</article>
   <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    {% browserid_js %}
    </body>
</html>

kind/templates/kind/detail.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
    </head>
    <body>
      <h1>{{ specification.spec_name }}</h1>

      {% render_table specification.requirement_set.all %}
      <!--
      <td>{{ requirement.heading_text }}</td>
      <td>{{ requirement.body_text }}</td>
      -->

    </body>
</html>

kind/templates/kind/index.html
{% load browserid %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'kind/style.css' %}" />
<html>
  <head>
    {% browserid_css %}
  </head>
    <body>
      {% browserid_info %}

  <header>
      <div class="authentication">
        {% if user.is_authenticated %}
          {% browserid_logout text='Logout' %}
        {% else %}
          {% browserid_login text='Login' color='dark' %}
        {% endif %}
      </div>
      <h1>Specification list</h1>
    </header>
<article>


{% if latest_spec_list %}
    <ul>
    {% for spec in latest_spec_list %}
        <li><a href="{% url 'kind:detail' spec.id %}">{{ spec.spec_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No specs are available.</p>
{% endif %}
</article>
   <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    {% browserid_js %}
    </body>
</html>